### ISSUE TITLE
Deprecated properties used, which prevent using gradle 7.0

### ISSUE THREAD

**Issue by riterdando** [zhurlik/gradle-jboss-modules-plugin#6]
I am currently using your plugin under gradle 6.3 and I get the following deprecation warning:

`Configure project :wildfly-groovy-module
The Distribution.baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the distributionBaseName property instead. See https://docs.gradle.org/6.3/dsl/org.gradle.api.distribution.Distribution.html#org.gradle.api.distribution.Distribution:baseName for more details.`

Your plugin itself applies the _distribution_ plugin and in order to be make it work under gradle 7.x you have to replace some deprecated properties.

I would be very happy if you could provide a new version without using the deprecated properties.
That way I can continue using your plugin

**Comment by zhurlik** [comment]
Please try this one [Version 1.1 ](https://plugins.gradle.org/plugin/com.github.zhurlik.jbossmodules)

**Comment by riterdando** [comment]
Thanks a lot, the new version solves the mentioned deprecation problems.

That was really fast!
